Name:           ros-indigo-geodesy
Version:        0.4.0
Release:        0%{?dist}
Summary:        ROS geodesy package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/geodesy
Source0:        %{name}-%{version}.tar.gz

Requires:       pyproj
Requires:       ros-indigo-geographic-msgs
Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-sensor-msgs
Requires:       ros-indigo-tf
Requires:       ros-indigo-unique-id
Requires:       ros-indigo-uuid-msgs
BuildRequires:  python-catkin_pkg
BuildRequires:  ros-indigo-angles
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-geographic-msgs
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-rosunit
BuildRequires:  ros-indigo-sensor-msgs
BuildRequires:  ros-indigo-tf
BuildRequires:  ros-indigo-unique-id
BuildRequires:  ros-indigo-uuid-msgs

%description
Python and C++ interfaces for manipulating geodetic coordinates.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Sep 18 2014 Jack O'Quin <jack.oquin@gmail.com> - 0.4.0-0
- Autogenerated by Bloom

* Sat Aug 30 2014 Jack O'Quin <jack.oquin@gmail.com> - 0.3.2-0
- Autogenerated by Bloom

